function main() {
  const g = global;
  const keys = Object.getOwnPropertyNames(g);
  for (const k of keys) {
    const o = g[k];
    console.log(typeof(o), k);
  }
}
/**
 * 
class Object
class Function      
class Array
class Number        
function parseFloat    
function parseInt      
number Infinity        
number NaN
undefined undefined    
class Boolean       
class String        
class Symbol        
class Date
class Promise       
class RegExp        
class Error
class AggregateError
class EvalError     
class RangeError    
class ReferenceError
class SyntaxError   
class TypeError     
class URIError      
object globalThis      
object JSON
object Math
object Intl
class ArrayBuffer   
class Uint8Array    
class Int8Array     
class Uint16Array   
class Int16Array    
class Uint32Array   
class Int32Array    
class Float32Array  
class Float64Array  
class Uint8ClampedArray
class BigUint64Array
class BigInt64Array
class DataView
class Map
class BigInt
class Set
class WeakMap
class WeakSet
class Proxy
object Reflect
class FinalizationRegistry
class WeakRef
function decodeURI
function decodeURIComponent
function encodeURI
function encodeURIComponent
function escape
function unescape
function eval
function isFinite
function isNaN
object console
object process
object global
class Buffer
class BroadcastChannel
function queueMicrotask
function clearImmediate
function setImmediate
function structuredClone
class URL
class URLSearchParams
class DOMException
class TextEncoder
class TextDecoder
class AbortController
class AbortSignal
class EventTarget
class Event
class MessageChannel
class MessagePort
class MessageEvent
function clearInterval
function clearTimeout
function setInterval
function setTimeout
function atob
function btoa
class Blob
class Performance
object performance
class ReadableStream
class ReadableStreamDefaultReader
class ReadableStreamBYOBReader
class ReadableStreamBYOBRequest
class ReadableByteStreamController
class ReadableStreamDefaultController
class TransformStream
class TransformStreamDefaultController
class WritableStream
class WritableStreamDefaultWriter
class WritableStreamDefaultController
class ByteLengthQueuingStrategy
class CountQueuingStrategy
class TextEncoderStream
class TextDecoderStream
class CompressionStream
class DecompressionStream
class SharedArrayBuffer
object Atomics
object WebAssembly
function fetch
class FormData
class Headers
class Request
class Response
 */

/**
class	AbortController
class	AbortSignal
class	AggregateError
class	Array
class	ArrayBuffer
class	BigInt
class	BigInt64Array
class	BigUint64Array
class	Blob
class	Boolean
class	BroadcastChannel
class	Buffer
class	ByteLengthQueuingStrategy
class	CompressionStream
class	CountQueuingStrategy
class	DataView
class	Date
class	DecompressionStream
class	DOMException
class	Error
class	EvalError
class	Event
class	EventTarget
class	FinalizationRegistry
class	Float32Array
class	Float64Array
class	FormData
class	Function
class	Headers
class	Int16Array
class	Int32Array
class	Int8Array
class	Map
class	MessageChannel
class	MessageEvent
class	MessagePort
class	Number
class	Object
class	Performance
class	Promise
class	Proxy
class	RangeError
class	ReadableByteStreamController
class	ReadableStream
class	ReadableStreamBYOBReader
class	ReadableStreamBYOBRequest
class	ReadableStreamDefaultController
class	ReadableStreamDefaultReader
class	ReferenceError
class	RegExp
class	Request
class	Response
class	Set
class	SharedArrayBuffer
class	String
class	Symbol
class	SyntaxError
class	TextDecoder
class	TextDecoderStream
class	TextEncoder
class	TextEncoderStream
class	TransformStream
class	TransformStreamDefaultController
class	TypeError
class	Uint16Array
class	Uint32Array
class	Uint8Array
class	Uint8ClampedArray
class	URIError
class	URL
class	URLSearchParams
class	WeakMap
class	WeakRef
class	WeakSet
class	WritableStream
class	WritableStreamDefaultController
class	WritableStreamDefaultWriter
function	atob
function	btoa
function	clearImmediate
function	clearInterval
function	clearTimeout
function	decodeURI
function	decodeURIComponent
function	encodeURI
function	encodeURIComponent
function	escape
function	eval
function	fetch
function	isFinite
function	isNaN
function	parseFloat
function	parseInt
function	queueMicrotask
function	setImmediate
function	setInterval
function	setTimeout
function	structuredClone
function	unescape
number	Infinity
number	NaN
object	Atomics
object	console
object	global
object	globalThis
object	Intl
object	JSON
object	Math
object	performance
object	process
object	Reflect
object	WebAssembly
undefined	undefined
 */
main();

export {};